/**
 * llm-wiki Raycast extension — search wiki pages.
 *
 * Reads the search-index.json generated by `llmwiki build`, or falls back
 * to a simple filesystem grep over wiki/ markdown files.
 */

import {
  ActionPanel,
  Action,
  List,
  getPreferenceValues,
  showToast,
  Toast,
  open,
} from "@raycast/api";
import { useState, useEffect } from "react";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Preferences {
  wikiDir: string;
  serverPort?: string;
}

interface WikiPage {
  title: string;
  path: string;
  section: string;
  snippet: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadSearchIndex(wikiDir: string): WikiPage[] | null {
  const indexPath = path.join(wikiDir, "site", "search-index.json");
  if (!fs.existsSync(indexPath)) return null;
  try {
    const raw = fs.readFileSync(indexPath, "utf-8");
    const entries = JSON.parse(raw) as Array<{
      title?: string;
      url?: string;
      body?: string;
    }>;
    return entries.map((e) => ({
      title: e.title || path.basename(e.url || "", ".html"),
      path: e.url || "",
      section: inferSection(e.url || ""),
      snippet: (e.body || "").slice(0, 200),
    }));
  } catch {
    return null;
  }
}

function inferSection(url: string): string {
  if (url.includes("/sources/")) return "Sources";
  if (url.includes("/entities/")) return "Entities";
  if (url.includes("/concepts/")) return "Concepts";
  if (url.includes("/syntheses/")) return "Syntheses";
  return "Wiki";
}

/**
 * Fallback: use grep to search .md files under wiki/.
 */
function grepWiki(wikiDir: string, query: string): WikiPage[] {
  if (!query || query.length < 2) return [];
  const wikiPath = path.join(wikiDir, "wiki");
  if (!fs.existsSync(wikiPath)) return [];

  try {
    const stdout = execSync(
      `grep -ril --include='*.md' ${JSON.stringify(query)} ${JSON.stringify(wikiPath)}`,
      { encoding: "utf-8", timeout: 5000 }
    );
    return stdout
      .trim()
      .split("\n")
      .filter(Boolean)
      .slice(0, 20)
      .map((filePath) => {
        const rel = path.relative(wikiPath, filePath);
        const content = fs.readFileSync(filePath, "utf-8");
        const titleMatch = content.match(/^#\s+(.+)$/m);
        return {
          title: titleMatch ? titleMatch[1] : path.basename(filePath, ".md"),
          path: rel,
          section: inferSection(rel),
          snippet: content.slice(0, 200).replace(/\n/g, " "),
        };
      });
  } catch {
    // grep returns exit code 1 when no matches — that's fine
    return [];
  }
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function SearchWiki() {
  const prefs = getPreferenceValues<Preferences>();
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<WikiPage[]>([]);
  const [indexPages, setIndexPages] = useState<WikiPage[] | null>(null);

  // Load search index once on mount
  useEffect(() => {
    const pages = loadSearchIndex(prefs.wikiDir);
    if (pages) {
      setIndexPages(pages);
    }
  }, []);

  // Search on query change
  useEffect(() => {
    if (!query) {
      setResults(indexPages || []);
      return;
    }

    if (indexPages) {
      // Client-side filter over the search index
      const lower = query.toLowerCase();
      setResults(
        indexPages.filter(
          (p) =>
            p.title.toLowerCase().includes(lower) ||
            p.snippet.toLowerCase().includes(lower)
        )
      );
    } else {
      // Fallback to grep
      setResults(grepWiki(prefs.wikiDir, query));
    }
  }, [query, indexPages]);

  const port = prefs.serverPort || "8765";

  return (
    <List
      searchBarPlaceholder="Search wiki pages..."
      onSearchTextChange={setQuery}
      throttle
    >
      {results.map((page) => (
        <List.Item
          key={page.path}
          title={page.title}
          subtitle={page.section}
          accessories={[{ text: page.path }]}
          actions={
            <ActionPanel>
              <Action.Open
                title="Open in Browser"
                target={`http://localhost:${port}/${page.path.replace(/\.md$/, ".html")}`}
              />
              <Action.Open
                title="Open Markdown"
                target={path.join(prefs.wikiDir, "wiki", page.path)}
              />
              <Action.CopyToClipboard
                title="Copy Path"
                content={page.path}
              />
            </ActionPanel>
          }
        />
      ))}
    </List>
  );
}
