#!/usr/bin/env python3
"""Alfred Script Filter for llm-wiki.

Searches the search-index.json generated by `llmwiki build` and returns
Alfred JSON feedback. Falls back to a simple file-title scan when the
index is unavailable.

Usage (from Alfred Script Filter):
    python3 search.py "{query}"

Environment variables:
    LLMWIKI_DIR — absolute path to the llm-wiki project root (required)
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def load_search_index(project_root: Path) -> list[dict] | None:
    """Load the pre-built search index from site/search-index.json."""
    index_path = project_root / "site" / "search-index.json"
    if not index_path.exists():
        return None
    try:
        return json.loads(index_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def scan_wiki_titles(project_root: Path) -> list[dict]:
    """Fallback: scan wiki/ for .md files and extract titles from headings."""
    wiki_dir = project_root / "wiki"
    if not wiki_dir.is_dir():
        return []
    results = []
    for md in sorted(wiki_dir.rglob("*.md")):
        if md.name.startswith("_"):
            continue
        # Extract first H1 as title
        title = md.stem
        try:
            for line in md.read_text(encoding="utf-8").splitlines():
                if line.startswith("# "):
                    title = line[2:].strip()
                    break
        except OSError:
            pass
        rel = md.relative_to(wiki_dir)
        section = rel.parts[0] if len(rel.parts) > 1 else "wiki"
        results.append(
            {
                "title": title,
                "path": str(rel),
                "section": section,
            }
        )
    return results


def search(query: str, entries: list[dict]) -> list[dict]:
    """Simple case-insensitive substring match."""
    if not query:
        return entries[:30]
    q = query.lower()
    scored = []
    for entry in entries:
        title = (entry.get("title") or "").lower()
        body = (entry.get("body") or entry.get("snippet") or "").lower()
        path_str = (entry.get("path") or entry.get("url") or "").lower()
        if q in title:
            scored.append((0, entry))  # title match ranks highest
        elif q in path_str:
            scored.append((1, entry))
        elif q in body:
            scored.append((2, entry))
    scored.sort(key=lambda x: x[0])
    return [e for _, e in scored[:20]]


def to_alfred_json(matches: list[dict], port: int = 8765) -> dict:
    """Format results as Alfred Script Filter JSON feedback."""
    items = []
    for m in matches:
        title = m.get("title") or m.get("path", "Untitled")
        path_str = m.get("path") or m.get("url") or ""
        html_path = path_str.replace(".md", ".html")
        url = f"http://localhost:{port}/{html_path}"
        subtitle = m.get("section", "")
        if body := (m.get("body") or m.get("snippet") or ""):
            subtitle = body[:80]

        items.append(
            {
                "uid": path_str,
                "title": title,
                "subtitle": subtitle,
                "arg": url,
                "autocomplete": title,
                "icon": {"path": "icon.png"},
                "text": {
                    "copy": url,
                    "largetype": title,
                },
            }
        )

    if not items:
        items.append(
            {
                "title": "No results found",
                "subtitle": "Try a different search term",
                "valid": False,
            }
        )

    return {"items": items}


def main() -> None:
    project_root = Path(os.environ.get("LLMWIKI_DIR", ".")).resolve()
    query = sys.argv[1] if len(sys.argv) > 1 else ""

    # Try the search index first, fall back to title scan
    index = load_search_index(project_root)
    if index is not None:
        entries = index
    else:
        entries = scan_wiki_titles(project_root)

    matches = search(query, entries)
    print(json.dumps(to_alfred_json(matches), ensure_ascii=False))


if __name__ == "__main__":
    main()
